### ISSUE TITLE
ability to create a custom draft order that's different from our default one, then toggle between the two views while drafting

### ISSUE THREAD

**Issue by itkinfo** [phillydorn/CAProject#10]

**Comment by phillydorn** [comment]
hey what does this mean

**Comment by itkinfo** [comment]
Kind of the same issue.

Default would be the list of teams in order based on Vegas odds.   Then you
could re-order them to fit your personal preference.  As teams get drafted
- they would be removed from both lists and you could see either your
  custom list or the list based on Vegas odds.

**Comment by phillydorn** [comment]
oh ok - not changing our draft order (1,2,3,4,5,6,6,5,4,3,2,1, etc)
